pull_request_rules:
- name: label scala-steward's PRs
  conditions:
  - author=scala-steward
  actions:
    label:
      add:
      - dependency-update
      remove: []
- name: merge scala-steward's PRs
  conditions:
  - author=scala-steward
  - status-success=Build And Test
  - "#files=1"
  actions:
    merge:
      method: squash
